apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: venue-catalog-staging

resources:
  - ../../base
  - patch-namespace.yaml

patches:
  - path: patch-ingress.yaml
  - path: patch-backend-infra.yaml

images:
  - name: venue-catalog-backend
    newName: venue-catalog-backend
    newTag: staging
  - name: venue-catalog-web
    newName: venue-catalog-web
    newTag: staging
