apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: venue-catalog
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls: []
  rules:
    - host: api.venue-catalog.nafuralabs.staging
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: venue-catalog-backend
                port:
                  number: 8085
    - host: catalog.nafuralabs.staging
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: venue-catalog-web
                port:
                  number: 80
