#!/usr/bin/env bash
# Mode B helpers — process locaux branchés sur infra staging (Docker Desktop).
# Usage:
#   bash toolchain/ops/dev-staging-local.sh [app-id] [front|back|full]
#   bash toolchain/ops/dev-staging-local.sh stop
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CTX="${KUBE_CONTEXT:-docker-desktop}"
INFRA_NS="nafura-infra-staging"
PF_DIR="${TMPDIR:-/tmp}/nafura-dev-up"
PF_PID_FILE="${PF_DIR}/port-forward.pids"
ENV_FILE="${ROOT}/secrets/dev-staging-local.env"

mkdir -p "$PF_DIR"

die() { echo "ERROR: $*" >&2; exit 1; }

stop_port_forwards() {
  if [[ -f "$PF_PID_FILE" ]]; then
    while read -r pid; do
      [[ -n "${pid:-}" ]] && kill "$pid" 2>/dev/null || true
    done <"$PF_PID_FILE"
    rm -f "$PF_PID_FILE"
    echo "Stopped previous port-forwards."
  fi
}

if [[ "${1:-}" == "stop" ]]; then
  stop_port_forwards
  exit 0
fi

APP_ID="${1:-sektor-btp}"
SCOPE="${2:-full}"

case "$SCOPE" in
  front|back|full) ;;
  *) die "scope must be front|back|full (got: $SCOPE)" ;;
esac

[[ "${ENV:-staging}" == "staging" ]] || die "dev-up only supports ENV=staging"
kubectl --context="$CTX" get ns "$INFRA_NS" >/dev/null 2>&1 \
  || die "namespace $INFRA_NS missing — run bootstrap-env first"

read_secret_field() {
  local section="$1"
  local key="$2"
  local secrets_file="$ROOT/secrets/nafura.secrets"
  [[ -f "$secrets_file" ]] || return 0
  awk -v sec="[$section]" -v key="$key" '
    $0 == sec { in_sec=1; next }
    /^\[/ { in_sec=0 }
    in_sec && index($0, key "=") == 1 { sub(/^[^=]+=/, ""); print; exit }
  ' "$secrets_file"
}

write_env_file_sektor() {
  local gemini_key=""
  gemini_key="$(read_secret_field "staging/platform/integrations/ai/gemini" "api_key")"
  if [[ -z "$gemini_key" && -n "${AI_GEMINI_API_KEY:-}" ]]; then
    gemini_key="$AI_GEMINI_API_KEY"
  fi

  cat >"$ENV_FILE" <<EOF
# Generated by toolchain/ops/dev-staging-local.sh — do not commit
# Usage: set -a; source secrets/dev-staging-local.env; set +a

POSTGRES_HOST=localhost
POSTGRES_DB=nafura_erp
POSTGRES_SCHEMA=public
POSTGRES_USER=nafura
POSTGRES_PASSWORD=nafura

KEYCLOAK_ISSUER_URI=http://iam.nafuralabs.staging/realms/iam-portal
KEYCLOAK_JWK_SET_URI=http://iam.nafuralabs.staging/realms/iam-portal/protocol/openid-connect/certs
KEYCLOAK_ADMIN_URL=http://iam.nafuralabs.staging
KEYCLOAK_ADMIN_USERNAME=admin
KEYCLOAK_ADMIN_PASSWORD=admin
KEYCLOAK_REALM=iam-portal
KEYCLOAK_CLIENT_ID=erp-web

# S3 API (port 9000 via ingress s3.*) — pas minio.* qui sert la console (9001)
DOCUMENTS_MINIO_ENDPOINT=http://s3.nafuralabs.staging
DOCUMENTS_MINIO_BUCKET=nafura-documents
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin

APP_FRONTEND_BASE_URL=http://localhost:4200
NAFURA_ONBOARDING_SKIP_EMAIL_VERIFICATION=true
# QA local auto-login (Mode B only — never set on K8s staging/prod)
# Owner qa@nafuralabs.local / tenant qa-local provisioned on boot when enabled
NAFURA_DEV_CURSOR_AUTH_ENABLED=true
NAFURA_DEV_CURSOR_AUTH_EMAIL=qa@nafuralabs.local
AI_GEMINI_API_KEY=$gemini_key
EOF
  if [[ -n "$gemini_key" ]]; then
    echo "Wrote $ENV_FILE (Gemini key present)"
  else
    echo "Wrote $ENV_FILE (WARNING: no AI_GEMINI_API_KEY — descriptif CPS uses section fallback)"
  fi
}

write_env_file_blanner() {
  local places_key=""
  places_key="$(read_secret_field "staging/apps/blanner/integrations" "google_places_api_key")"
  if [[ -z "$places_key" && -n "${GOOGLE_PLACES_API_KEY:-}" ]]; then
    places_key="$GOOGLE_PLACES_API_KEY"
  fi

  cat >"$ENV_FILE" <<EOF
# Generated by toolchain/ops/dev-staging-local.sh — do not commit
# Usage: set -a; source secrets/dev-staging-local.env; set +a

POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=nafura_blanner
POSTGRES_SCHEMA=public
POSTGRES_USER=nafura
POSTGRES_PASSWORD=nafura
SERVER_PORT=8080
GOOGLE_PLACES_API_KEY=$places_key
CORS_ALLOWED_ORIGIN_PATTERNS=http://localhost:*,http://127.0.0.1:*,http://10.0.2.2:*,https://*.nafuralabs.staging
EOF
  if [[ -n "$places_key" ]]; then
    echo "Wrote $ENV_FILE (Google Places key present)"
  else
    echo "Wrote $ENV_FILE (WARNING: no GOOGLE_PLACES_API_KEY — Places autocomplete will fail)"
  fi
}

write_env_file_venue_catalog() {
  local db_name db_schema db_user db_pass
  local minio_bucket minio_user minio_password places_key
  db_name="$(read_secret_field "staging/apps/venue-catalog/database" "name")"
  db_schema="$(read_secret_field "staging/apps/venue-catalog/database" "schema")"
  db_user="$(read_secret_field "staging/apps/venue-catalog/database" "user")"
  db_pass="$(read_secret_field "staging/apps/venue-catalog/database" "pass")"
  minio_bucket="$(read_secret_field "staging/apps/venue-catalog/object-storage" "bucket")"
  minio_user="$(read_secret_field "staging/apps/venue-catalog/object-storage" "user")"
  minio_password="$(read_secret_field "staging/apps/venue-catalog/object-storage" "password")"
  places_key="$(read_secret_field "staging/apps/venue-catalog/integrations" "google_places_api_key")"

  db_name="${db_name:-nafura_venue_catalog}"
  db_schema="${db_schema:-public}"
  db_user="${db_user:-nafura}"
  db_pass="${db_pass:-nafura}"
  minio_bucket="${minio_bucket:-venue-catalog-media}"
  minio_user="${minio_user:-minioadmin}"
  minio_password="${minio_password:-minioadmin}"
  if [[ -z "$places_key" && -n "${GOOGLE_PLACES_API_KEY:-}" ]]; then
    places_key="$GOOGLE_PLACES_API_KEY"
  fi

  cat >"$ENV_FILE" <<EOF
# Generated by toolchain/ops/dev-staging-local.sh — do not commit
# Usage: set -a; source secrets/dev-staging-local.env; set +a

POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=$db_name
POSTGRES_SCHEMA=$db_schema
POSTGRES_USER=$db_user
POSTGRES_PASSWORD=$db_pass

REDIS_HOST=localhost
REDIS_PORT=6380

# S3 API through the staging ingress; cluster-local MinIO DNS is not resolvable here.
DOCUMENTS_MINIO_ENDPOINT=http://s3.nafuralabs.staging
DOCUMENTS_MINIO_BUCKET=$minio_bucket
MINIO_ROOT_USER=$minio_user
MINIO_ROOT_PASSWORD=$minio_password

SERVER_PORT=8085
KEYCLOAK_ISSUER_URI=http://iam.nafuralabs.staging/realms/iam-portal
KEYCLOAK_JWK_SET_URI=http://iam.nafuralabs.staging/realms/iam-portal/protocol/openid-connect/certs
GOOGLE_PLACES_API_KEY=$places_key
EOF
  if [[ -n "$places_key" ]]; then
    echo "Wrote $ENV_FILE (Venue Catalog secrets and Places key present)"
  else
    echo "Wrote $ENV_FILE (WARNING: no GOOGLE_PLACES_API_KEY — Places import will fail)"
  fi
}

start_port_forwards() {
  local postgres_pid redis_pid=""
  stop_port_forwards
  : >"$PF_PID_FILE"

  kubectl --context="$CTX" -n "$INFRA_NS" port-forward svc/postgres 5432:5432 \
    >/tmp/nafura-pf-postgres.log 2>&1 &
  postgres_pid=$!
  echo "$postgres_pid" >>"$PF_PID_FILE"

  if [[ "$APP_ID" == "venue-catalog" ]]; then
    kubectl --context="$CTX" -n "$INFRA_NS" port-forward svc/redis 6380:6379 \
      >/tmp/nafura-pf-redis.log 2>&1 &
    redis_pid=$!
    echo "$redis_pid" >>"$PF_PID_FILE"
  fi

  sleep 1
  if ! kill -0 "$postgres_pid" 2>/dev/null; then
    die "postgres port-forward failed — see /tmp/nafura-pf-postgres.log"
  fi
  if [[ -n "$redis_pid" ]]; then
    if ! kill -0 "$redis_pid" 2>/dev/null; then
      die "redis port-forward failed — see /tmp/nafura-pf-redis.log"
    fi
    echo "Port-forward: localhost:6380 → $INFRA_NS/redis (pid $redis_pid)"
  fi
  echo "Port-forward: localhost:5432 → $INFRA_NS/postgres (pid $postgres_pid)"
}

print_recipe_sektor() {
  case "$SCOPE" in
    front)
      cat <<'EOF'
# Front local (Cursor QA — auto-login qa@nafuralabs.local)
cd products/sektor-btp/web
npm run start:erp:cursor
# → http://127.0.0.1:4200  |  API http://localhost:8082
# Keycloak staging-local (manuel) : npm run start:erp:staging-local
EOF
      ;;
    back)
      cat <<EOF
# Backend local
set -a; source "$ENV_FILE"; set +a
./gradlew.bat :sektor:app:bootRun
# → http://localhost:8082/actuator/health
EOF
      ;;
    full)
      cat <<EOF
# Terminal 1 — backend
set -a; source "$ENV_FILE"; set +a
./gradlew.bat :sektor:app:bootRun

# Terminal 2 — frontend (Cursor QA — auto-login qa@nafuralabs.local)
cd products/sektor-btp/web
npm run start:erp:cursor

# URLs
#   App:  http://127.0.0.1:4200
#   API:  http://localhost:8082
# Keycloak staging-local (manuel) : npm run start:erp:staging-local
EOF
      ;;
  esac
}

print_recipe_blanner() {
  case "$SCOPE" in
    front)
      cat <<'EOF'
# Flutter local → back local (démarrer le back en parallèle si besoin)
cd products/blanner/blanner_flutter
flutter run --dart-define=API_BASE_URL=http://10.0.2.2:8080/api
# iOS / Chrome: --dart-define=API_BASE_URL=http://localhost:8080/api
EOF
      ;;
    back)
      cat <<EOF
# Backend local
set -a; source "$ENV_FILE"; set +a
./gradlew.bat :blanner:app:bootRun
# → http://localhost:8080/actuator/health
# Prérequis: make provision-db APP=blanner (ou onboard-app blanner)
EOF
      ;;
    full)
      cat <<EOF
# Terminal 1 — backend
set -a; source "$ENV_FILE"; set +a
./gradlew.bat :blanner:app:bootRun

# Terminal 2 — Flutter (Android emulator)
cd products/blanner/blanner_flutter
flutter run --dart-define=API_BASE_URL=http://10.0.2.2:8080/api

# URLs
#   API:      http://localhost:8080
#   Health:   http://localhost:8080/actuator/health
#   Swagger:  http://localhost:8080/swagger-ui/index.html
#   Staging API (pods): http://api.blanner.nafuralabs.staging
EOF
      ;;
  esac
}

print_recipe_venue_catalog() {
  if [[ "$SCOPE" == "front" ]]; then
    cat <<'EOF'
# Frontend local (Mode B) — API local via proxy, IAM staging
cd products/venue-catalog/web
npm start
# URL: http://127.0.0.1:4210  (proxy /api → localhost:8085)
# Auth: useDevJwt=true (staging-local) — bouton "Continuer (dev JWT)"
EOF
    return
  fi

  if [[ "$SCOPE" == "full" ]]; then
    cat <<EOF
# Backend local
set -a; source "$ENV_FILE"; set +a
./gradlew.bat :venue-catalog:app:bootRun

# Frontend (autre terminal)
cd products/venue-catalog/web && npm start

# URLs
#   Web:          http://127.0.0.1:4210
#   API:          http://localhost:8085
#   Health:       http://localhost:8085/actuator/health
#   Staging API:  http://api.venue-catalog.nafuralabs.staging
# Prérequis: make provision-db APP=venue-catalog (Flyway runs at startup)
EOF
    return
  fi

  cat <<EOF
# Backend local
set -a; source "$ENV_FILE"; set +a
./gradlew.bat :venue-catalog:app:bootRun

# URLs
#   API:          http://localhost:8085
#   Health:       http://localhost:8085/actuator/health
#   Staging API:  http://api.venue-catalog.nafuralabs.staging
# Prérequis: make provision-db APP=venue-catalog (Flyway runs at startup)
EOF
}

case "$APP_ID" in
  sektor-btp|erp)
    write_env_file_sektor
    ;;
  blanner)
    write_env_file_blanner
    ;;
  venue-catalog)
    write_env_file_venue_catalog
    ;;
  *)
    die "dev-up Mode B not implemented for $APP_ID (supported: sektor-btp, blanner, venue-catalog)"
    ;;
esac

if [[ "$SCOPE" == "back" || "$SCOPE" == "full" ]]; then
  start_port_forwards
fi

cat <<EOF

=== dev-up $APP_ID SCOPE=$SCOPE ===
Mode B: process locaux → infra staging (pas de rebuild image).

Env file : $ENV_FILE
Stop PF  : bash toolchain/ops/dev-staging-local.sh stop

EOF

case "$APP_ID" in
  sektor-btp|erp) print_recipe_sektor ;;
  blanner) print_recipe_blanner ;;
  venue-catalog) print_recipe_venue_catalog ;;
esac

echo ""
echo "Validation pods: make stg-up SCOPE=$SCOPE APP=$APP_ID"
