#!/usr/bin/env bash
# Mode B helpers — process locaux branchés sur infra staging (Docker Desktop).
# Usage:
#   bash toolchain/ops/dev-staging-local.sh [app-id] [front|back|full]
#   bash toolchain/ops/dev-staging-local.sh stop
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CTX="${KUBE_CONTEXT:-docker-desktop}"
INFRA_NS="nafura-infra-staging"
PF_DIR="${TMPDIR:-/tmp}/nafura-dev-up"
PF_PID_FILE="${PF_DIR}/port-forward.pids"
ENV_FILE="${ROOT}/secrets/dev-staging-local.env"

mkdir -p "$PF_DIR"

die() { echo "ERROR: $*" >&2; exit 1; }

stop_port_forwards() {
  if [[ -f "$PF_PID_FILE" ]]; then
    while read -r pid; do
      [[ -n "${pid:-}" ]] && kill "$pid" 2>/dev/null || true
    done <"$PF_PID_FILE"
    rm -f "$PF_PID_FILE"
    echo "Stopped previous port-forwards."
  fi
}

if [[ "${1:-}" == "stop" ]]; then
  stop_port_forwards
  exit 0
fi

APP_ID="${1:-sektor-btp}"
SCOPE="${2:-full}"

case "$SCOPE" in
  front|back|full) ;;
  *) die "scope must be front|back|full (got: $SCOPE)" ;;
esac

[[ "${ENV:-staging}" == "staging" ]] || die "dev-up only supports ENV=staging"
kubectl --context="$CTX" get ns "$INFRA_NS" >/dev/null 2>&1 \
  || die "namespace $INFRA_NS missing — run bootstrap-env first"

write_env_file() {
  cat >"$ENV_FILE" <<EOF
# Generated by toolchain/ops/dev-staging-local.sh — do not commit
# Usage: set -a; source secrets/dev-staging-local.env; set +a

POSTGRES_HOST=localhost
POSTGRES_DB=nafura_erp
POSTGRES_SCHEMA=public
POSTGRES_USER=nafura
POSTGRES_PASSWORD=nafura

KEYCLOAK_ISSUER_URI=http://iam.nafuralabs.staging/realms/iam-portal
KEYCLOAK_JWK_SET_URI=http://iam.nafuralabs.staging/realms/iam-portal/protocol/openid-connect/certs
KEYCLOAK_ADMIN_URL=http://iam.nafuralabs.staging
KEYCLOAK_ADMIN_USERNAME=admin
KEYCLOAK_ADMIN_PASSWORD=admin
KEYCLOAK_REALM=iam-portal
KEYCLOAK_CLIENT_ID=erp-web

# S3 API (port 9000 via ingress s3.*) — pas minio.* qui sert la console (9001)
DOCUMENTS_MINIO_ENDPOINT=http://s3.nafuralabs.staging
DOCUMENTS_MINIO_BUCKET=nafura-documents
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin

APP_FRONTEND_BASE_URL=http://localhost:4200
NAFURA_ONBOARDING_SKIP_EMAIL_VERIFICATION=true
EOF
  echo "Wrote $ENV_FILE"
}

start_port_forwards() {
  stop_port_forwards
  : >"$PF_PID_FILE"

  kubectl --context="$CTX" -n "$INFRA_NS" port-forward svc/postgres 5432:5432 \
    >/tmp/nafura-pf-postgres.log 2>&1 &
  echo $! >>"$PF_PID_FILE"

  sleep 1
  if ! kill -0 "$(head -1 "$PF_PID_FILE")" 2>/dev/null; then
    die "postgres port-forward failed — see /tmp/nafura-pf-postgres.log"
  fi
  echo "Port-forward: localhost:5432 → $INFRA_NS/postgres (pid $(head -1 "$PF_PID_FILE"))"
}

write_env_file
if [[ "$SCOPE" == "back" || "$SCOPE" == "full" ]]; then
  start_port_forwards
fi

cat <<EOF

=== dev-up $APP_ID SCOPE=$SCOPE ===
Mode B: process locaux → infra staging (pas de rebuild image).

Env file : $ENV_FILE
Stop PF  : bash toolchain/ops/dev-staging-local.sh stop

EOF

case "$SCOPE" in
  front)
    cat <<'EOF'
# Front local
cd products/sektor-btp/web
npm run start:erp:staging-local
# → http://127.0.0.1:4200  |  API http://localhost:8082  |  IAM http://iam.nafuralabs.staging
EOF
    ;;
  back)
    cat <<EOF
# Backend local
set -a; source "$ENV_FILE"; set +a
./gradlew.bat :sektor:app:bootRun
# → http://localhost:8082/actuator/health
EOF
    ;;
  full)
    cat <<EOF
# Terminal 1 — backend
set -a; source "$ENV_FILE"; set +a
./gradlew.bat :sektor:app:bootRun

# Terminal 2 — frontend
cd products/sektor-btp/web
npm run start:erp:staging-local

# URLs
#   App:  http://127.0.0.1:4200
#   API:  http://localhost:8082
#   IAM:  http://iam.nafuralabs.staging
EOF
    ;;
esac

echo ""
echo "Validation pods: make stg-up SCOPE=$SCOPE APP=$APP_ID"
