// Generated by nafops for app "erp" — rebuilt on `nafops build app --app erp --web` (dev/K8s config).

export const environment = {
  production: false,
  apiBaseUrl: 'http://api.erp.nafura.local',
  keycloakUrl: 'http://iam.nafura.local',
  keycloakRealm: 'iam-portal',
  keycloakClientId: "erp-web",
  devAuthBypass: false,
  onboardingV2Enabled: true,
  devAuthUser: {
    id: '',
    email: '',
    firstName: '',
    lastName: '',
    tenantId: '',
    tenantName: '',
    tenantSlug: '',
  },
};
