apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sektor-demo

resources:
  - ../../base
  - patch-namespace.yaml

patches:
  - path: patch-backend-deployment.yaml
  - path: patch-frontend-local.yaml
  - path: patch-ingress.yaml

images:
  - name: sektor-btp-backend
    newName: europe-west9-docker.pkg.dev/gen-lang-client-0875291215/nafura/sektor-btp-backend
    newTag: demo
  - name: sektor-btp-web
    newName: europe-west9-docker.pkg.dev/gen-lang-client-0875291215/nafura/sektor-btp-web
    newTag: demo
