apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: usage-ops-staging

resources:
  - ../../base
  - patch-namespace.yaml

patches:
  - path: patch-ingress.yaml
  - path: patch-backend-infra.yaml

images:
  - name: usage-ops-backend
    newName: usage-ops-backend
    newTag: staging
  - name: usage-ops-web
    newName: usage-ops-web
    newTag: staging
