apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usage-ops
spec:
  rules:
    - host: usage-ops.nafuralabs.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: usage-ops-backend
                port:
                  number: 8087
          - path: /
            pathType: Prefix
            backend:
              service:
                name: usage-ops-web
                port:
                  number: 80
