apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
spec:
  template:
    spec:
      containers:
        - name: vault-init
          env:
            - name: VAULT_ENV
              value: "staging"
            - name: INFRA_NAMESPACE
              value: "nafura-infra-staging"
