apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mbs-studio

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: mbs-studio-web
    newName: mbs-studio-web
    newTag: staging
