plugins {
    id 'java-library'
}

dependencies {
    implementation 'ma.nafuralabs:framework:0.1.0-SNAPSHOT'
    implementation 'ma.nafuralabs:authorization:0.1.0-SNAPSHOT'
    implementation 'ma.nafuralabs:identity:0.1.0-SNAPSHOT'
    implementation 'ma.nafuralabs:tenancy:0.1.0-SNAPSHOT'
    implementation 'ma.nafuralabs:iam:0.1.0-SNAPSHOT'
    implementation 'ma.nafuralabs:app-settings:0.1.0-SNAPSHOT'
    implementation 'ma.nafuralabs:sysconfig:0.1.0-SNAPSHOT'
    implementation 'ma.nafuralabs:doc-manager:0.1.0-SNAPSHOT'
    implementation 'ma.nafuralabs:notification:0.1.0-SNAPSHOT'
    implementation 'ma.nafuralabs:llm-provider:0.1.0-SNAPSHOT'
    implementation 'ma.nafuralabs:ai-agent-api:0.1.0-SNAPSHOT'

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.postgresql:postgresql'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
