// Generated by nafgen (generate-compose-apps.mjs) for app "erp" — do not edit by hand.
// Rebuilt when you run: nafgen apply, nafops provision/reconcile, or `nafops build app --app erp --web` with compose config.

export const environment = {
  production: false,
  apiBaseUrl: 'http://localhost:8082',
  keycloakUrl: 'http://localhost:8080',
  keycloakRealm: 'iam-portal',
  keycloakClientId: "erp-web",
  devAuthBypass: false,
  onboardingV2Enabled: true,
  devAuthUser: {
    id: '',
    email: '',
    firstName: '',
    lastName: '',
    tenantId: '',
    tenantName: '',
    tenantSlug: '',
  },
};
