rootProject.name = "nafura-platform"

fun includePlatform(path: String) {
    val relative = path.removePrefix(":platform:").replace(':', '/')
    include(path)
    project(path).projectDir = file(relative)
}

includePlatform(":platform:core:framework")
includePlatform(":platform:core:authorization")
includePlatform(":platform:core:identity")
includePlatform(":platform:core:scope")
includePlatform(":platform:core:tenancy")
includePlatform(":platform:core:observability")

includePlatform(":platform:features:configuration:settings")
includePlatform(":platform:features:configuration:sysconfig")
includePlatform(":platform:features:administration:iam")
includePlatform(":platform:features:administration:subscription")
includePlatform(":platform:features:administration:usage")
includePlatform(":platform:features:ai:ai-agent-api")
includePlatform(":platform:features:ai:ai-agent-runtime")
includePlatform(":platform:features:ai:ai-conversation")
includePlatform(":platform:features:ai:llm-provider")
includePlatform(":platform:features:app-settings")
includePlatform(":platform:features:user-settings")
includePlatform(":platform:features:collaboration:audit")
include(":platform:commentaire")
project(":platform:commentaire").projectDir = file("commentaire")
includePlatform(":platform:features:collaboration:doc-manager")
include(":platform:documents")
project(":platform:documents").projectDir = file("documents")
include(":platform:impression")
project(":platform:impression").projectDir = file("impression")
includePlatform(":platform:features:collaboration:notification")
includePlatform(":platform:features:collaboration:tagging")
include(":platform:approbation")
project(":platform:approbation").projectDir = file("approbation")
includePlatform(":platform:features:collaboration:webhook")
include(":platform:document-extraction")
project(":platform:document-extraction").projectDir = file("document-extraction")
includePlatform(":platform:features:foundation:geo")
includePlatform(":platform:integrations:google-places")
includePlatform(":platform:core:job-runner")
