rootProject.name = "nafura-platform"

fun includePlatform(path: String) {
    val relative = path.removePrefix(":platform:").replace(':', '/')
    include(path)
    project(path).projectDir = file(relative)
}

includePlatform(":platform:core:framework")
includePlatform(":platform:core:authorization")
includePlatform(":platform:core:identity")
includePlatform(":platform:core:scope")
includePlatform(":platform:core:tenancy")
includePlatform(":platform:core:observability")

includePlatform(":platform:features:configuration:settings")
includePlatform(":platform:features:configuration:sysconfig")
includePlatform(":platform:features:administration:iam")
includePlatform(":platform:features:administration:subscription")
includePlatform(":platform:features:administration:usage")
includePlatform(":platform:features:ai:ai-agent-api")
includePlatform(":platform:features:ai:ai-agent-runtime")
includePlatform(":platform:features:ai:ai-conversation")
includePlatform(":platform:features:ai:llm-provider")
includePlatform(":platform:features:app-settings")
includePlatform(":platform:features:user-settings")
includePlatform(":platform:features:collaboration:audit")
includePlatform(":platform:features:collaboration:comment")
includePlatform(":platform:features:collaboration:doc-manager")
includePlatform(":platform:features:collaboration:notification")
includePlatform(":platform:features:collaboration:tagging")
includePlatform(":platform:features:collaboration:workflow")
includePlatform(":platform:features:collaboration:webhook")
includePlatform(":platform:features:documents:doc-extractor")
includePlatform(":platform:features:foundation:geo")
includePlatform(":platform:integrations:google-places")
includePlatform(":platform:core:job-runner")
