apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/apps/erp/backend-service-account.yaml
  - ../../../../base/apps/erp/backend-deployment.yaml
  - ../../../../base/apps/erp/backend-service.yaml
  - ../../../../base/apps/erp/frontend-deployment.yaml
  - ../../../../base/apps/erp/frontend-service.yaml

images:
  - name: erp-backend
    newName: erp-backend
    newTag: dev
  - name: erp-web
    newName: erp-web
    newTag: dev
