apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erp-ingress
spec:
  rules:
    - host: api.erp.nafura.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: erp-backend
                port:
                  number: 8082
    - host: erp.nafura.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: erp-web
                port:
                  number: 80
