import type { DetailFieldConfig } from '@lib/anatomy/types';
import type { Ouvrage } from '@applications/erp/etudes/models';

export const FIELDS: DetailFieldConfig<Ouvrage>[] = [
  {
    key: 'code',
    label: 'Code',
    type: 'text',
    required: true,
    readonlyOnEdit: true,
    width: 'md',
    validators: [{ type: 'maxLength', value: 30 }],
  },
  {
    key: 'designation',
    label: 'Désignation',
    type: 'text',
    required: true,
    width: 'lg',
    validators: [{ type: 'maxLength', value: 200 }],
  },
  {
    key: 'category',
    label: 'Catégorie',
    type: 'select',
    required: true,
    width: 'md',
    lookupKey: 'ouvrageCategory',
  },
  {
    key: 'unite',
    label: 'Unité',
    type: 'select',
    required: true,
    width: 'sm',
    options: [
      { value: 'm³', label: 'm³' },
      { value: 'm²', label: 'm²' },
      { value: 'ml', label: 'ml' },
      { value: 'U', label: 'U' },
      { value: 'kg', label: 'kg' },
      { value: 'T', label: 'T' },
      { value: 'h', label: 'h' },
      { value: 'ff', label: 'ff (forfait)' },
    ],
  },
  {
    key: 'prixUnitaireHt',
    label: 'Prix unitaire HT (MAD)',
    type: 'money-ma',
    width: 'md',
    readonly: true,
    hint: 'Calculé automatiquement à partir du sous-détail',
  },
  {
    key: 'fraisGenerauxPercent',
    label: 'Frais généraux (%)',
    type: 'number',
    width: 'sm',
    defaultValue: 8,
    validators: [{ type: 'min', value: 0 }, { type: 'max', value: 100 }],
  },
  {
    key: 'beneficePercent',
    label: 'Bénéfice (%)',
    type: 'number',
    width: 'sm',
    defaultValue: 7,
    validators: [{ type: 'min', value: 0 }, { type: 'max', value: 100 }],
  },
  {
    key: 'isActive',
    label: 'Actif',
    type: 'toggle',
    width: 'sm',
    defaultValue: true,
  },
  {
    key: 'notes',
    label: 'Notes',
    type: 'textarea',
    width: 'full',
  },
  {
    key: 'composants',
    label: 'Sous-détail',
    type: 'custom',
    width: 'full',
    defaultValue: [],
  },
  {
    key: 'dpuComposants',
    label: 'DPU',
    type: 'custom',
    width: 'full',
    defaultValue: [],
  },
  {
    key: 'dpuHistorique',
    label: 'Historique DPU',
    type: 'custom',
    width: 'full',
    defaultValue: [],
    visible: false,
  },
];
