apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-minio: "secret/data/nafura/prod/infra/minio"
        vault.hashicorp.com/agent-inject-template-minio: |
          {{- with secret "secret/data/nafura/prod/infra/minio" -}}
          export MINIO_ROOT_USER="{{ .Data.data.root_user }}"
          export MINIO_ROOT_PASSWORD="{{ .Data.data.root_password }}"
          {{- end }}
