apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-db: "secret/data/nafura/prod/infra/postgres"
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secret/data/nafura/prod/infra/postgres" -}}
          export POSTGRES_USER="{{ .Data.data.username }}"
          export POSTGRES_PASSWORD="{{ .Data.data.password }}"
          {{- end }}
