apiVersion: v1
kind: Service
metadata:
  name: zenith-web
  namespace: zenith-prod
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: zenith-web
  namespace: zenith-prod
subsets:
  - addresses:
      - ip: 10.88.130.150
    ports:
      - port: 80
        protocol: TCP
