plugins {
    id 'java-library'
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation project(':platform:core:framework')
    implementation project(':platform:core:authorization-api')
    implementation project(':platform:notification')
    implementation project(':platform:approbation')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
