apiVersion: apps/v1
kind: Deployment
metadata:
  name: blanner-backend
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-address: "http://vault.nafura-infra-prod.svc:8200"
        vault.hashicorp.com/agent-inject-secret-app-db: "secret/data/nafura/prod/apps/blanner/database"
        vault.hashicorp.com/agent-inject-template-app-db: |
          {{- with secret "secret/data/nafura/prod/apps/blanner/database" -}}
          export POSTGRES_DB="{{ .Data.data.name }}"
          export POSTGRES_SCHEMA="{{ .Data.data.schema }}"
          export POSTGRES_USER="{{ .Data.data.user }}"
          export POSTGRES_PASSWORD="{{ .Data.data.pass }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-app-integrations: "secret/data/nafura/prod/apps/blanner/integrations"
        vault.hashicorp.com/agent-inject-template-app-integrations: |
          {{- with secret "secret/data/nafura/prod/apps/blanner/integrations" -}}
          export GOOGLE_PLACES_API_KEY="{{ .Data.data.google_places_api_key }}"
          {{- end }}
    spec:
      containers:
        - name: blanner-backend
          imagePullPolicy: Always
          env:
            - name: POSTGRES_HOST
              value: postgres.nafura-infra-prod.svc
            - name: CORS_ALLOWED_ORIGIN_PATTERNS
              value: "https://*.nafuralabs.com"
