apiVersion: apps/v1
kind: Deployment
metadata:
  name: sektor-btp-backend
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-address: "http://vault.nafura-infra-staging.svc:8200"
    spec:
      containers:
        - name: sektor-btp-backend
          env:
            - name: KEYCLOAK_ISSUER_URI
              value: http://iam.nafuralabs.staging/realms/iam-portal
            - name: APP_FRONTEND_BASE_URL
              value: http://sektor.nafuralabs.staging
            - name: NAFURA_ONBOARDING_SKIP_EMAIL_VERIFICATION
              value: "true"
