apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nafura-vitrine-staging

resources:
  - ../../base
  - patch-namespace.yaml

patches:
  - path: patch-ingress.yaml
  - path: patch-ingress-tls.yaml

images:
  - name: zenith-web
    newName: zenith-web
    newTag: staging
