apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blanner-staging

resources:
  - backend-service-account.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - ingress.yaml

images:
  - name: blanner-backend
    newName: blanner-backend
    newTag: staging
