plugins {
    id 'java-library'
}

dependencies {
    implementation project(':platform:core:framework')
    implementation project(':platform:features:ai:ai-agent-api')
    implementation project(':platform:features:ai:ai-agent-runtime')

    implementation 'org.springframework.boot:spring-boot-starter'
}
