CREATE TABLE IF NOT EXISTS chantiers (
    id                          VARCHAR(100) PRIMARY KEY,
    tenant_id                   UUID NOT NULL,
    code                        VARCHAR(50) NOT NULL,
    label                       VARCHAR(255) NOT NULL,
    description                 TEXT,
    chantier_type               VARCHAR(30) NOT NULL DEFAULT 'BATIMENT',
    client_id                   VARCHAR(100),
    client_name                 VARCHAR(255),
    marche_numero               VARCHAR(100),
    type_ccag_t                 VARCHAR(30),
    moa_id                      VARCHAR(100),
    moe_id                      VARCHAR(100),
    bet_id                      VARCHAR(100),
    adresse                     VARCHAR(500),
    ville                       VARCHAR(120),
    latitude                    NUMERIC(10, 7),
    longitude                   NUMERIC(10, 7),
    date_demarrage              DATE,
    duree_mois                  INTEGER,
    date_fin_prevue             DATE,
    date_fin_reelle             DATE,
    montant_ht                  NUMERIC(18, 4) NOT NULL DEFAULT 0,
    taux_tva                    NUMERIC(8, 4) NOT NULL DEFAULT 20,
    taux_rg                     NUMERIC(8, 4),
    taux_ras                    NUMERIC(8, 4),
    taux_avance                 NUMERIC(8, 4),
    avancement_percent          NUMERIC(8, 4) NOT NULL DEFAULT 0,
    status                      VARCHAR(40) NOT NULL DEFAULT 'BROUILLON',
    chef_chantier_user_id       VARCHAR(100),
    chef_chantier_name          VARCHAR(255),
    conducteur_travaux_user_id  VARCHAR(100),
    conducteur_travaux_name     VARCHAR(255),
    ingenieur_user_id           VARCHAR(100),
    ingenieur_name              VARCHAR(255),
    societe_id                  VARCHAR(100),
    is_active                   BOOLEAN NOT NULL DEFAULT true,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_chantiers_tenant_code UNIQUE (tenant_id, code)
);

CREATE INDEX IF NOT EXISTS idx_chantiers_tenant_status ON chantiers(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_chantiers_tenant_client ON chantiers(tenant_id, client_id);
CREATE INDEX IF NOT EXISTS idx_chantiers_tenant_societe ON chantiers(tenant_id, societe_id);
