-- Refonte workflow Étude : codes techniques anglais + journal d'action.
-- Mapping ancien → nouveau (données lab / staging existantes).

ALTER TABLE dossiers_etude DROP CONSTRAINT IF EXISTS dossiers_etude_status_chk;

UPDATE dossiers_etude SET status = CASE status
    WHEN 'BROUILLON' THEN 'DRAFT'
    WHEN 'A_DECIDER' THEN 'PENDING_ASSIGNMENT'
    WHEN 'NE_PAS_ETUDIER' THEN 'REJECTED'
    WHEN 'AFFECTE' THEN 'ASSIGNED'
    WHEN 'REJETE_CHIFFRAGE' THEN 'STUDY_REJECTED'
    WHEN 'EN_ETUDE' THEN 'IN_PROGRESS'
    WHEN 'SUSPENDU' THEN 'SUSPENDED'
    WHEN 'A_AVIS_EXECUTION' THEN 'IN_PROGRESS'
    WHEN 'EN_VALIDATION' THEN 'COMPLETED'
    WHEN 'VALIDEE' THEN 'FINANCIALLY_APPROVED'
    WHEN 'DEVIS_GENERE' THEN 'FINAL_APPROVED'
    WHEN 'GAGNE' THEN 'FINAL_APPROVED'
    WHEN 'CONVERTIE' THEN 'FINAL_APPROVED'
    WHEN 'PERDU' THEN 'ARCHIVED'
    WHEN 'ANNULE' THEN 'ARCHIVED'
    ELSE status
END
WHERE status IN (
    'BROUILLON','A_DECIDER','NE_PAS_ETUDIER','AFFECTE','REJETE_CHIFFRAGE',
    'EN_ETUDE','SUSPENDU','A_AVIS_EXECUTION','EN_VALIDATION','VALIDEE',
    'DEVIS_GENERE','GAGNE','CONVERTIE','PERDU','ANNULE');

UPDATE transitions_etude SET ancien_statut = CASE ancien_statut
    WHEN 'BROUILLON' THEN 'DRAFT'
    WHEN 'A_DECIDER' THEN 'PENDING_ASSIGNMENT'
    WHEN 'NE_PAS_ETUDIER' THEN 'REJECTED'
    WHEN 'AFFECTE' THEN 'ASSIGNED'
    WHEN 'REJETE_CHIFFRAGE' THEN 'STUDY_REJECTED'
    WHEN 'EN_ETUDE' THEN 'IN_PROGRESS'
    WHEN 'SUSPENDU' THEN 'SUSPENDED'
    WHEN 'A_AVIS_EXECUTION' THEN 'IN_PROGRESS'
    WHEN 'EN_VALIDATION' THEN 'COMPLETED'
    WHEN 'VALIDEE' THEN 'FINANCIALLY_APPROVED'
    WHEN 'DEVIS_GENERE' THEN 'FINAL_APPROVED'
    WHEN 'GAGNE' THEN 'FINAL_APPROVED'
    WHEN 'CONVERTIE' THEN 'FINAL_APPROVED'
    WHEN 'PERDU' THEN 'ARCHIVED'
    WHEN 'ANNULE' THEN 'ARCHIVED'
    ELSE ancien_statut
END;

UPDATE transitions_etude SET nouveau_statut = CASE nouveau_statut
    WHEN 'BROUILLON' THEN 'DRAFT'
    WHEN 'A_DECIDER' THEN 'PENDING_ASSIGNMENT'
    WHEN 'NE_PAS_ETUDIER' THEN 'REJECTED'
    WHEN 'AFFECTE' THEN 'ASSIGNED'
    WHEN 'REJETE_CHIFFRAGE' THEN 'STUDY_REJECTED'
    WHEN 'EN_ETUDE' THEN 'IN_PROGRESS'
    WHEN 'SUSPENDU' THEN 'SUSPENDED'
    WHEN 'A_AVIS_EXECUTION' THEN 'IN_PROGRESS'
    WHEN 'EN_VALIDATION' THEN 'COMPLETED'
    WHEN 'VALIDEE' THEN 'FINANCIALLY_APPROVED'
    WHEN 'DEVIS_GENERE' THEN 'FINAL_APPROVED'
    WHEN 'GAGNE' THEN 'FINAL_APPROVED'
    WHEN 'CONVERTIE' THEN 'FINAL_APPROVED'
    WHEN 'PERDU' THEN 'ARCHIVED'
    WHEN 'ANNULE' THEN 'ARCHIVED'
    ELSE nouveau_statut
END;

ALTER TABLE dossiers_etude ALTER COLUMN status SET DEFAULT 'DRAFT';

ALTER TABLE dossiers_etude ADD CONSTRAINT dossiers_etude_status_chk CHECK (status IN (
    'DRAFT','PENDING_ASSIGNMENT','REJECTED','ASSIGNED','STUDY_REJECTED',
    'IN_PROGRESS','SUSPENDED','COMPLETED','FINANCIALLY_APPROVED','FINANCIALLY_REJECTED',
    'FINAL_APPROVED','FINAL_REJECTED','ARCHIVED'));

ALTER TABLE transitions_etude ADD COLUMN IF NOT EXISTS action VARCHAR(40);

COMMENT ON COLUMN dossiers_etude.status IS
    'Workflow BC Étude. Gagné/Perdu/chantier sont hors de cette machine à états.';
