import type { ExtractionSchemaBundle } from './extraction-schema.types';

const posteSchema = {
  type: 'object' as const,
  required: ['designation'],
  properties: {
    designation: { type: ['string', 'null'] as const, title: 'Désignation article' },
    unite: { type: ['string', 'null'] as const, title: 'Unité' },
    quantite: { type: ['number', 'null'] as const, title: 'Quantité' },
    prixUnitaireHt: { type: ['number', 'null'] as const, title: 'PU HT' },
  },
};

/** Leaf grouping node (depth 2): designation + postes only. */
const leafLotSchema = {
  type: 'object' as const,
  required: ['designation'],
  properties: {
    designation: { type: ['string', 'null'] as const, title: 'Désignation sous-sous-lot' },
    postes: {
      type: 'array' as const,
      title: 'Postes / articles',
      items: posteSchema,
    },
  },
};

/** Mid grouping node (depth 1): may contain children (depth 2) and/or postes. */
const midLotSchema = {
  type: 'object' as const,
  required: ['designation'],
  properties: {
    designation: { type: ['string', 'null'] as const, title: 'Désignation sous-lot' },
    children: {
      type: 'array' as const,
      title: 'Sous-sous-lots',
      items: leafLotSchema,
    },
    postes: {
      type: 'array' as const,
      title: 'Postes / articles',
      items: posteSchema,
    },
  },
};

export const LOT_CHANTIER_EXTRACTION_SCHEMA: ExtractionSchemaBundle = {
  name: 'Import lots chantier (hiérarchique)',
  description: 'Import nested chantier structure: lots, sous-lots, sous-sous-lots and postes.',
  arrayPath: 'lots',
  instructions: `You are a document extraction assistant for construction bill of quantities (BPDE / bordereau des prix).
Return ONLY valid JSON matching the provided JSON Schema.

HIERARCHY (critical):
- "lots" = root / parent lots (e.g. headers "LOT 1 : Terrassement").
- Each lot may contain nested "children" (regroupement sections without unit) and/or "postes" (articles).
- Nesting may go up to 3 grouping levels: lot → children → children.
- "postes" = sellable articles with unit (and usually qty / unit price); attach them to the matching grouping node.
- Do NOT flatten articles into the top-level lots array.
- Preserve hierarchy only through the nested "children" and "postes" arrays.
- Ignore source numbering such as 1.1, 1.2 or 2.3. Do not return it as a business code or identifier.
- Return only business values: designation, unite, quantite and prixUnitaireHt.
- IDs, technical codes, ordering and parent-child relations are generated by the application.
- Do NOT invent quantities or prices. Use null when absent.`,
  dataSchema: {
    type: 'object',
    required: ['lots'],
    properties: {
      lots: {
        type: 'array',
        minItems: 0,
        items: {
          type: 'object',
          required: ['designation'],
          properties: {
            designation: { type: ['string', 'null'], title: 'Désignation lot' },
            children: {
              type: 'array',
              title: 'Sous-lots',
              items: midLotSchema,
            },
            postes: {
              type: 'array',
              title: 'Postes / articles',
              items: posteSchema,
            },
          },
        },
      },
    },
  },
  presentationSchema: {
    importPolicy: 'PARTIAL',
    rootView: 'TREE_TABLE',
    sections: [],
    arrays: [
      {
        path: 'lots',
        title: 'Lots',
        columns: [
          { path: 'designation', label: 'Désignation' },
          { path: 'unite', label: 'Unité', widthPx: 80 },
          { path: 'quantite', label: 'Qté', widthPx: 80 },
          { path: 'prixUnitaireHt', label: 'PU HT', widthPx: 100 },
        ],
      },
    ],
    tree: {
      path: 'lots',
      childrenPaths: ['children', 'postes'],
      columns: [
        { path: 'designation', label: 'Désignation' },
        { path: 'unite', label: 'Unité', widthPx: 80 },
        { path: 'quantite', label: 'Qté', widthPx: 80 },
        { path: 'prixUnitaireHt', label: 'PU HT', widthPx: 100 },
      ],
      levelLabels: {
        lots: 'Lot',
        children: 'Sous-lot',
        postes: 'Poste',
      },
    },
    hierarchyHint: [
      { level: 'lot', label: 'Lot parent', fields: ['designation'] },
      { level: 'sousLot', label: 'Sous-lot', fields: ['designation'] },
      {
        level: 'poste',
        label: 'Poste / article',
        fields: ['designation', 'unite', 'quantite', 'prixUnitaireHt'],
      },
    ],
  },
};
