apiVersion: apps/v1
kind: Deployment
metadata:
  name: sektor-btp-backend
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-address: "http://vault.nafura-infra-staging.svc:8200"
    spec:
      containers:
        - name: sektor-btp-backend
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: postgres.nafura-infra-staging.svc
            - name: NAFURA_GOTENBERG_URL
              value: http://gotenberg.nafura-infra-staging.svc:3000
            - name: KEYCLOAK_JWK_SET_URI
              value: http://keycloak.nafura-infra-staging.svc:8080/realms/iam-portal/protocol/openid-connect/certs
            - name: KEYCLOAK_ADMIN_URL
              value: http://keycloak.nafura-infra-staging.svc:8080
