apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbs-studio-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mbs-studio-web
  template:
    metadata:
      labels:
        app: mbs-studio-web
    spec:
      containers:
        - name: mbs-studio-web
          image: mbs-studio-web:staging
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
