apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: venue-catalog-staging

resources:
  - backend-service-account.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

images:
  - name: venue-catalog-backend
    newName: venue-catalog-backend
    newTag: staging
  - name: venue-catalog-web
    newName: venue-catalog-web
    newTag: staging
