const assert=require('node:assert/strict');
const fs=require('node:fs');
const ts=require('typescript');
const source=fs.readFileSync(__dirname+'/planning-market.ts','utf8');
const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const mod={exports:{}};new Function('exports','require','module',compiled)(mod.exports,require,mod);
const {marketPlanning}=mod.exports;
const node=(id,nature='VENDU',children=[])=>({id,code:id,designation:id,nature,type:children.length?'LOT':'POSTE',enfants:children,totaux:{avancementPercent:25}});
const a={id:'a',forme:'ACTIVITE',dateDebut:'2026-09-14',dateFin:'2026-09-16',rattachements:[{posteId:'p'},{posteId:'q'}]};
const rows=marketPlanning([node('lot','VENDU',[node('p'),node('q'),node('missing'),node('internal','INTERNE')])],[a]);
assert.equal(rows[0].activityCount,1,'multi-post activity must not be counted twice at lot level');
assert.equal(rows[0].plannedPosts,2);assert.equal(rows[0].totalPosts,3);
assert.equal(rows[0].start,'2026-09-14');assert.equal(rows[0].finish,'2026-09-16');
assert.equal(rows.find(r=>r.id==='missing').start,null,'unplanned sold posts remain visible');
assert.ok(!rows.some(r=>r.id==='internal'),'internal costs excluded');
assert.deepEqual(rows.find(r=>r.id==='p').parentIds,['lot']);
assert.equal(rows[0].progress,25,'progress is the source value, not a task average');
assert.equal(marketPlanning([node('p')],[{...a,forme:'PHASE'}])[0].activityCount,0);
assert.equal(marketPlanning([node('p')],[{...a,forme:'JALON',rattachements:[]}])[0].start,null);
console.log('Planning marché : 11 assertions réussies.');
