const assert=require('node:assert/strict');
const fs=require('node:fs');const ts=require('typescript');
const compiled=ts.transpileModule(fs.readFileSync(__dirname+'/planning-supply.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const mod={exports:{}};new Function('exports','require','module',compiled)(mod.exports,require,mod);
const {supplyAlerts}=mod.exports;
const row={neededDate:'2026-09-14',launchDate:'2026-09-07',demandId:null,demandStatus:null,sourceUnavailable:false,orders:[]};
assert.equal(supplyAlerts(row,'2026-09-07').length,0,'launch date today is not late');
assert.match(supplyAlerts(row,'2026-09-08')[0],/lancement dépassée/);
const approved={...row,demandId:'d',demandDate:row.neededDate,demandStatus:'APPROUVEE'};
assert.equal(supplyAlerts(approved,'2026-09-08').length,0);
assert.match(supplyAlerts({...approved,demandDate:'2026-09-13'},'2026-09-08')[0],/différente/);
const order={id:'bc',number:'BC-1',status:'PARTIELLEMENT_LIVRE',expectedDate:'2026-09-16',receipts:[]};
assert.match(supplyAlerts({...approved,orders:[order]},'2026-09-08')[0],/après la date du besoin/);
assert.equal(supplyAlerts({...approved,orders:[{...order,status:'LIVRE'}]},'2026-09-20').length,0,'source delivered order does not trigger forecast warnings');
assert.match(supplyAlerts({...approved,orders:[{...order,status:'ANNULE'}]},'2026-09-20')[0],/annulées/);
assert.match(supplyAlerts({...row,sourceUnavailable:true},'2026-09-20')[0],/inaccessible/);
assert.equal(supplyAlerts({...approved,orders:[order]},'2026-09-20').length,2,'partial receipt retains both schedule warnings');
assert.match(supplyAlerts({...approved,demandStatus:'REJETEE'},'2026-09-01')[0],/rejetée/,'rejection must remain visible before launch date');
console.log('Approvisionnements : 10 scénarios réussis.');
