import type { DetailFieldConfig } from '@platform/lib/anatomy/types';
import type { Devis } from '@app/etudes/models';
import { villeSelectOptions } from '@platform/lib/referentiels/geo-ma';

export const FIELDS: DetailFieldConfig<Devis>[] = [
  {
    key: 'numero',
    label: 'N° devis',
    type: 'text',
    readonly: true,
    width: 'md',
    placeholder: 'Auto-généré',
  },
  {
    key: 'version',
    label: 'Version',
    type: 'number',
    readonly: true,
    width: 'sm',
    defaultValue: 1,
  },
  {
    key: 'clientId',
    label: 'Client',
    type: 'select',
    required: true,
    width: 'lg',
    lookupKey: 'clients',
    searchable: true,
  },
  {
    key: 'contactClientId',
    label: 'Contact client',
    type: 'select',
    width: 'md',
    lookupKey: 'partnerContacts',
    clearable: true,
    searchable: true,
  },
  {
    key: 'objet',
    label: 'Objet du devis',
    type: 'text',
    required: true,
    width: 'full',
  },
  {
    key: 'ville',
    label: 'Ville',
    type: 'select',
    width: 'md',
    options: villeSelectOptions(),
    clearable: true,
    searchable: true,
  },
  {
    key: 'dossierEtudeId',
    label: 'Dossier d\'étude',
    type: 'text',
    readonly: true,
    width: 'md',
    visible: (form) => !!form.dossierEtudeId,
  },
  {
    key: 'dpgfId',
    label: 'DPGF source',
    type: 'text',
    readonly: true,
    width: 'md',
    visible: (form) => !!form.dpgfId,
  },
  {
    key: 'bibliothequeReference',
    label: 'Réf. bibliothèque',
    type: 'text',
    readonly: true,
    width: 'md',
    visible: (form) => !!form.bibliothequeReference,
  },
  {
    key: 'dateEmission',
    label: 'Date émission',
    type: 'date',
    required: true,
    width: 'md',
  },
  {
    key: 'dateValidite',
    label: 'Date validité',
    type: 'date',
    required: true,
    width: 'md',
  },
  {
    key: 'conditionsPaiement',
    label: 'Conditions de paiement',
    type: 'textarea',
    required: true,
    width: 'full',
  },
  {
    key: 'delaiExecutionJours',
    label: 'Délai exécution (jours)',
    type: 'number',
    width: 'md',
  },
  {
    key: 'tvaTaux',
    label: 'Taux TVA (%)',
    type: 'number',
    width: 'sm',
    defaultValue: 20,
  },
  {
    key: 'remiseGlobalePercent',
    label: 'Remise globale (%)',
    type: 'number',
    width: 'sm',
  },
  {
    key: 'totalHt',
    label: 'Total HT (MAD)',
    type: 'money-ma',
    readonly: true,
    width: 'md',
  },
  {
    key: 'totalTva',
    label: 'TVA (MAD)',
    type: 'money-ma',
    readonly: true,
    width: 'md',
  },
  {
    key: 'totalTtc',
    label: 'Total TTC (MAD)',
    type: 'money-ma',
    readonly: true,
    width: 'md',
  },
  {
    key: 'motifRefus',
    label: 'Motif de refus',
    type: 'textarea',
    width: 'full',
    visible: (form) => form.status === 'PERDU',
  },
  {
    key: 'notes',
    label: 'Notes internes',
    type: 'textarea',
    width: 'full',
  },
  {
    key: 'lignes',
    label: 'DPGF — Décomposition du prix global et forfaitaire',
    type: 'custom',
    width: 'full',
    defaultValue: [],
  },
];
