apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nafura-vitrine-prod

resources:
  - ../../base
  - patch-namespace.yaml

patches:
  - path: patch-ingress.yaml
  - path: patch-ingress-tls.yaml

images:
  - name: mbs-studio-web
    newName: 54.36.183.106:30500/nafura/mbs-studio-web
    newTag: prod
