apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: build-intelligence-staging

resources:
  - ../../base
  - patch-namespace.yaml

patches:
  - path: patch-ingress.yaml
  - path: patch-backend-infra.yaml

images:
  - name: build-intelligence-backend
    newName: build-intelligence-backend
    newTag: staging
  - name: build-intelligence-web
    newName: build-intelligence-web
    newTag: staging
