apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-intelligence-backend
spec:
  template:
    spec:
      containers:
        - name: build-intelligence-backend
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: postgres.nafura-infra-staging.svc
            - name: POSTGRES_USER
              value: nafura
            - name: POSTGRES_PASSWORD
              value: nafura
            - name: REDIS_HOST
              value: redis.nafura-infra-staging.svc
            - name: DOCUMENTS_MINIO_ENDPOINT
              value: http://minio.nafura-infra-staging.svc:9000
            - name: DOCUMENTS_MINIO_BUCKET
              value: build-intelligence-documents
            - name: MINIO_ROOT_USER
              value: minioadmin
            - name: MINIO_ROOT_PASSWORD
              value: minioadmin
            - name: KEYCLOAK_ISSUER_URI
              value: http://iam.nafuralabs.staging/realms/iam-portal
            - name: KEYCLOAK_JWK_SET_URI
              value: http://keycloak.nafura-infra-staging.svc:8080/realms/iam-portal/protocol/openid-connect/certs
            - name: SEKTOR_API_BASE_URL
              value: http://sektor-btp-backend.sektor-staging.svc:8082
