apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: build-intelligence
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/hsts: "false"
    nginx.ingress.kubernetes.io/hsts-max-age: "0"
spec:
  ingressClassName: nginx
  tls: []
  rules:
    - host: build-intelligence.nafuralabs.staging
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: build-intelligence-backend
                port:
                  number: 8086
          - path: /
            pathType: Prefix
            backend:
              service:
                name: build-intelligence-web
                port:
                  number: 80
