export type ProScreen =
  | 'pro-login'
  | 'pro-dashboard'
  | 'pro-access-requests'
  | 'pro-bookings-list'
  | 'pro-booking-detail'
  | 'pro-door-checkin'
  | 'pro-tables'
  | 'pro-events-list'
  | 'pro-event-edit'
  | 'pro-no-access'
  | 'pro-access-request'
  | 'pro-tenant-suspended'
  | 'pro-venue-settings'
  | 'pro-tickets-list'
  | 'pro-reviews'
