ALTER TABLE factures_client ADD COLUMN IF NOT EXISTS retenue_garantie_taux NUMERIC(8, 4) NOT NULL DEFAULT 0;
ALTER TABLE factures_client ADD COLUMN IF NOT EXISTS retenue_garantie_montant NUMERIC(18, 4) NOT NULL DEFAULT 0;
ALTER TABLE factures_client ADD COLUMN IF NOT EXISTS resorption_avance_montant NUMERIC(18, 4) NOT NULL DEFAULT 0;
ALTER TABLE factures_client ADD COLUMN IF NOT EXISTS net_a_payer_ht NUMERIC(18, 4) NOT NULL DEFAULT 0;
ALTER TABLE factures_client ADD COLUMN IF NOT EXISTS ras_taux NUMERIC(8, 4) NOT NULL DEFAULT 0;
ALTER TABLE factures_client ADD COLUMN IF NOT EXISTS ras_montant NUMERIC(18, 4) NOT NULL DEFAULT 0;
ALTER TABLE factures_client ADD COLUMN IF NOT EXISTS marche_public BOOLEAN NOT NULL DEFAULT false;
